# Generated by Django 4.0.2 on 2022-03-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nib',
            field=models.IntegerField(blank=True, db_column='NIB', max_length=255, null=True),
        ),
    ]
