# Generated by Django 4.0.2 on 2022-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0003_alter_administrador_parqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nib',
            field=models.IntegerField(blank=True, db_column='NIB', null=True),
        ),
    ]
