# Generated by Django 4.0.2 on 2022-03-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0004_alter_cliente_nib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registomovimento',
            name='hora_de_inicio',
        ),
        migrations.RemoveField(
            model_name='registomovimento',
            name='hora_de_termino',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_de_inicio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_de_termino',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_de_nascimento',
            field=models.DateTimeField(blank=True, db_column='Data de nascimento', null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_de_inicio',
            field=models.DateTimeField(blank=True, db_column='Data de inicio', null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_de_termino',
            field=models.DateTimeField(blank=True, db_column='Data de termino', null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_de_vencimento',
            field=models.DateTimeField(blank=True, db_column='Data de vencimento', null=True),
        ),
        migrations.AlterField(
            model_name='periodicidade',
            name='hora_de_inicio',
            field=models.TimeField(blank=True, db_column='Hora de inicio', null=True),
        ),
        migrations.AlterField(
            model_name='periodicidade',
            name='hora_de_termino',
            field=models.TimeField(blank=True, db_column='Hora de termino', null=True),
        ),
        migrations.AlterField(
            model_name='registomovimento',
            name='data_de_entrada',
            field=models.DateTimeField(auto_now_add=True, db_column='Data de entrada', null=True),
        ),
        migrations.AlterField(
            model_name='registomovimento',
            name='data_de_saida',
            field=models.DateTimeField(blank=True, db_column='Data de saida', null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_de_inicio',
            field=models.DateTimeField(blank=True, db_column='Data de inicio', null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_de_termino',
            field=models.DateTimeField(blank=True, db_column='Data de termino', null=True),
        ),
    ]
