# Generated by Django 4.0.2 on 2022-03-10 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0005_remove_registomovimento_hora_de_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registomovimento',
            name='data_de_entrada',
            field=models.DateTimeField(blank=True, db_column='Data de entrada', default=datetime.datetime.now, null=True),
        ),
    ]
