# Generated by Django 4.0.2 on 2022-03-10 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0007_alter_registomovimento_data_de_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registomovimento',
            name='data_de_entrada',
            field=models.DateTimeField(db_column='Data de entrada', default=datetime.datetime.now),
        ),
    ]
