# Generated by Django 4.0.2 on 2022-04-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0009_contrato_parqueid_registomovimento_parqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parque',
            name='nome',
            field=models.CharField(blank=True, db_column='Nome', max_length=255, null=True, unique='True'),
        ),
    ]
