# Generated by Django 4.0.2 on 2022-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0013_alter_parque_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parque',
            name='morada',
            field=models.CharField(blank=True, db_column='Morada', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
