# Generated by Django 4.0.2 on 2022-04-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0014_alter_parque_morada_alter_zona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
