# Generated by Django 4.0.2 on 2022-04-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0015_alter_zona_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parque',
            name='cidade',
            field=models.CharField(blank=True, db_column='Cidade', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='parque',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='parque',
            name='distrito',
            field=models.CharField(blank=True, db_column='Distrito', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parque',
            name='estado',
            field=models.CharField(blank=True, db_column='Estado', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parque',
            name='pais',
            field=models.CharField(blank=True, db_column='Pais', max_length=50, null=True),
        ),
    ]
