# Generated by Django 4.0.2 on 2022-05-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0016_parque_cidade_parque_codigo_postal_parque_distrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='parqueid',
            field=models.ForeignKey(db_column='ParqueID', default=1, on_delete=django.db.models.deletion.CASCADE, to='parque.parque'),
        ),
    ]
