# Generated by Django 4.0.2 on 2022-05-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0019_alter_lugar_contratoid_alter_lugar_reservaid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parque',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='parque',
            name='pais',
        ),
    ]
