# Generated by Django 4.0.2 on 2022-06-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0020_remove_parque_distrito_remove_parque_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('faturaid', models.IntegerField(db_column='FaturaID')),
                ('reclamacao', models.CharField(blank=True, db_column='Reclamacao', max_length=255, null=True)),
            ],
        ),
    ]
