# Generated by Django 4.0.2 on 2022-06-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0021_reclamacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parque',
            name='estado',
            field=models.CharField(db_column='Estado', default='Aberto', max_length=50),
        ),
    ]
