# Generated by Django 4.0.2 on 2022-06-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0023_alter_lugar_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='estado',
            field=models.CharField(blank=True, db_column='Estado', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parque',
            name='estado',
            field=models.CharField(blank=True, db_column='Estado', max_length=50, null=True),
        ),
    ]
