# Generated by Django 4.0.2 on 2022-06-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0025_alter_lugar_estado_alter_parque_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='numero_do_lugar',
            field=models.IntegerField(blank=True, db_column='Numero do lugar', null=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='numero_da_zona',
            field=models.IntegerField(blank=True, db_column='Numero da zona', null=True),
        ),
    ]
