# Generated by Django 4.0.2 on 2022-06-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0027_parque_foto_alter_lugar_numero_do_lugar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parque',
            name='foto',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to=''),
        ),
    ]
